<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.props" />

  <PropertyGroup>
    <AssemblyName>OniDataDump</AssemblyName>
    <RootNamespace>OniDataDump</RootNamespace>
    <Version>0.2.0</Version>
    <ReferenceImageConversion>true</ReferenceImageConversion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameLibsFolder)\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.targets" />

</Project>
